// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';


function activate(oni) {
  var config = oni.configuration;
  var startCommand = config.getValue("ocaml.langServerCommand", "ocaml-language-server");
  var startOptions = {
    command: startCommand,
    args: /* :: */[
      "--stdio",
      /* [] */0
    ]
  };
  var getInitializationOptions = function (filePath) {
    return Promise.resolve({
                clientName: "ocaml",
                rootPath: filePath
              });
  };
  return oni.createLanguageClient(startOptions, getInitializationOptions);
}

exports.activate = activate;
/* No side effect */
