// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var LanguageClient = /* module */[];

var Configuration = /* module */[];

var Oni = /* module */[
  /* LanguageClient */LanguageClient,
  /* Configuration */Configuration
];

function a(x) {
  return x + 1 | 0;
}

function b(x) {
  return ((x + 1 | 0) << 1);
}

function c(x) {
  return Caml_int32.imul(x + 1 | 0, 3);
}

exports.Oni = Oni;
exports.a   = a;
exports.b   = b;
exports.c   = c;
/* No side effect */
