#! /usr/bin/env node

var path = require("path")
var spawn = require("child_process").spawn
const os = require("os"),
      fs = require("fs");

let processOptions = {}
let log = require("path").join(__dirname, "out.log")
let out = fs.openSync(log, "a")
let err = fs.openSync(log, "a")
processOptions.detached = true
processOptions.stdio = ["ignore", out, err]

// Check for Windows, assume macOS/Windows otherwise
const isWindows = os.platform() === "win32";
const electronBinFile = isWindows ? "electron.cmd" : "electron"
var electronPath = path.join(__dirname, "..", "node_modules", ".bin", electronBinFile)
var args = process.argv.slice(2);
args.unshift(path.resolve(path.join(__dirname, "..", "main.js")))

// In Windows, directly call into the electron executable - otherwise we"ll end up with a floating node console
const windowsElectronPath = path.join(__dirname, "..", "node_modules", "electron", "dist", "electron.exe")
let spawnProcess = isWindows ? windowsElectronPath : electronPath
let spawnProcessOptions = isWindows ? {} : processOptions

let child = spawn(spawnProcess, args, processOptions)
child.unref()

child.on("error", (err) => console.log(err))
child.on("exit", (code) => process.exit(code));

process.exit(0)
