#!/usr/bin/env node

var path = require('path')
var spawn = require('child_process').spawn
const os = require("os");

// Check for Windows, assume macOS/Windows otherwise
const isWindows = os.platform() === "win32";
const electronBinFile = isWindows ? "electron.cmd" : "electron"
var electronPath = path.join(__dirname, "..", "node_modules", ".bin", electronBinFile)
var args = process.argv.slice(2);
args.unshift(path.resolve(path.join(__dirname, "..", "main.js")))

var child = spawn(electronPath, args)
child.stdout.pipe(process.stdout)
process.stdin.pipe(child.stdin)

child.on("exit", (code) => process.exit(code));
